import {
  SiReact, SiTypescript, SiJavascript, SiHtml5, SiSass,
  SiThreedotjs, SiNodedotjs, SiPython, SiGo, SiRust,
  SiPostgresql, SiRedis, SiGit, SiDocker,
  SiOpengl, SiLinux,
  FiCode, FiCpu,
} from '@/shared/ui/atoms/Icon';
import { DiJava } from '@/shared/ui/atoms/Icon';
import type { IconType } from 'react-icons';
import type { SkillData } from './skill-graph';

export const ICON_MAP: Record<string, IconType> = {
  React: SiReact, TypeScript: SiTypescript, JavaScript: SiJavascript,
  'HTML/CSS': SiHtml5, SCSS: SiSass, 'Three.js': SiThreedotjs,
  R3F: FiCode, 'Node.js': SiNodedotjs, Python: SiPython,
  Go: SiGo, Rust: SiRust, Java: DiJava,
  PostgreSQL: SiPostgresql, Redis: SiRedis,
  Git: SiGit, Docker: SiDocker,
  WebGPU: FiCode,
  CUDA: FiCpu, OpenGL: SiOpengl, Linux: SiLinux,
  C: FiCode, 'C++': FiCode, 'C#': FiCode, Luau: FiCode,
};

export const SKILLS_DATA: SkillData[] = [
  {
    name: 'React',
    group: 'frontend',
    category: 'framework',
    level: 4,
    difficulty: 3,
    desc: 'Component-driven UIs with hooks, context, and state machines.',
    funLevel: 'can build a SPA before coffee gets cold',
    related: ['TypeScript', 'JavaScript', 'R3F'],
    projects: ['nexagon'],
  },
  {
    name: 'TypeScript',
    group: 'frontend',
    category: 'language',
    level: 4,
    difficulty: 3,
    desc: 'Type-safe JavaScript for maintainable large-scale apps.',
    funLevel: 'types everything, even the types',
    related: ['React', 'JavaScript', 'Node.js'],
    projects: [],
  },
  {
    name: 'JavaScript',
    group: 'frontend',
    category: 'language',
    level: 5,
    difficulty: 2,
    desc: 'Core language of the web — ES6+ features and async patterns.',
    funLevel: 'speaks fluent callback',
    related: ['TypeScript', 'React', 'Node.js'],
    projects: [],
  },
  {
    name: 'HTML/CSS',
    group: 'frontend',
    category: 'language',
    level: 5,
    difficulty: 1,
    desc: 'Semantic markup, responsive layouts, and modern CSS.',
    funLevel: 'can center a div (finally)',
    related: ['SCSS'],
    projects: ['nexagon'],
  },
  {
    name: 'SCSS',
    group: 'frontend',
    category: 'framework',
    level: 4,
    difficulty: 2,
    desc: 'SASS-powered stylesheets with variables, mixins, and nesting.',
    funLevel: 'nests CSS like inception',
    related: ['HTML/CSS'],
    projects: [],
  },
  {
    name: 'Three.js',
    group: 'frontend',
    category: 'graphics',
    level: 3,
    difficulty: 4,
    desc: 'WebGL 3D rendering, shaders, and interactive scenes.',
    funLevel: 'makes triangles dance on screen',
    related: ['R3F', 'WebGPU', 'JavaScript'],
    projects: ['nexagon'],
  },
  {
    name: 'R3F',
    group: 'frontend',
    category: 'framework',
    level: 3,
    difficulty: 4,
    desc: 'React-three-fiber — declarative Three.js in React.',
    funLevel: 'declarative 3D without the headaches',
    related: ['Three.js', 'React'],
    projects: [],
  },
  {
    name: 'C/C++',
    group: 'frontend',
    category: 'language',
    level: 4,
    difficulty: 5,
    desc: 'Systems programming and performance-critical applications.',
    funLevel: 'segfaults with confidence',
    related: ['C#'],
    projects: [],
  },
  {
    name: 'C#',
    group: 'frontend',
    category: 'language',
    level: 3,
    difficulty: 3,
    desc: 'Modern, type-safe language for Windows and cross-platform development.',
    funLevel: 'writes code that compiles on the third try',
    related: ['C/C++'],
    projects: [],
  },
  {
    name: 'Node.js',
    group: 'backend',
    category: 'runtime',
    level: 4,
    difficulty: 3,
    desc: 'Server-side JS runtime for APIs and tooling.',
    funLevel: 'npm install solves 90% of problems',
    related: ['TypeScript', 'JavaScript', 'PostgreSQL', 'Redis'],
    projects: ['nexagon'],
  },
  {
    name: 'Python',
    group: 'backend',
    category: 'language',
    level: 3,
    difficulty: 2,
    desc: 'Scripting, automation, and backend services.',
    funLevel: 'imports their way to victory',
    related: ['Docker', 'Linux'],
    projects: [],
  },
  {
    name: 'Go',
    group: 'backend',
    category: 'language',
    level: 2,
    difficulty: 3,
    desc: 'Performant, concurrent systems and CLI tools.',
    funLevel: 'goroutines go brrr',
    related: ['Docker', 'Linux'],
    projects: [],
  },
  {
    name: 'Rust',
    group: 'backend',
    category: 'language',
    level: 4,
    difficulty: 5,
    desc: 'Memory-safe systems programming with zero-cost abstractions.',
    funLevel: 'fights the borrow checker daily',
    related: ['WebGPU', 'Linux'],
    projects: ['nexagon'],
  },
  {
    name: 'Java',
    group: 'backend',
    category: 'language',
    level: 2,
    difficulty: 3,
    desc: 'Enterprise-grade applications and Android development.',
    funLevel: 'writes once, debugs everywhere',
    related: ['PostgreSQL'],
    projects: ['bank-rest-api-app'],
  },
  {
    name: 'PostgreSQL',
    group: 'backend',
    category: 'database',
    level: 3,
    difficulty: 3,
    desc: 'Relational databases with advanced querying.',
    funLevel: 'SELECT wisdom FROM brain WHERE skill = 3',
    related: ['Node.js', 'Redis'],
    projects: ['nexagon'],
  },
  {
    name: 'Redis',
    group: 'backend',
    category: 'database',
    level: 3,
    difficulty: 2,
    desc: 'In-memory caching and pub/sub messaging.',
    funLevel: 'things go fast when you forget them',
    related: ['Node.js', 'PostgreSQL'],
    projects: ['nexagon'],
  },
  {
    name: 'Luau',
    group: 'backend',
    category: 'language',
    level: 4,
    difficulty: 3,
    desc: 'Scripting language for Roblox game development.',
    funLevel: 'makes Roblox do things it shouldnt',
    related: ['TypeScript'],
    projects: ['gmod-roblox', 'bloxingbad'],
  },
  {
    name: 'Git',
    group: 'tools',
    category: 'DevOps',
    level: 4,
    difficulty: 2,
    desc: 'Version control and collaborative development workflows.',
    funLevel: 'git push --force is a lifestyle',
    related: ['Linux'],
    projects: ['nexagon', 'bank-rest-api-app'],
  },
  {
    name: 'Docker',
    group: 'tools',
    category: 'DevOps',
    level: 3,
    difficulty: 3,
    desc: 'Containerized deployment and reproducible environments.',
    funLevel: 'works on my container',
    related: ['Linux', 'Node.js'],
    projects: ['nexagon', 'bank-rest-api-app'],
  },
  {
    name: 'WebGPU',
    group: 'tools',
    category: 'graphics',
    level: 2,
    difficulty: 5,
    desc: 'Next-gen GPU compute and rendering API.',
    funLevel: 'future-proofing one API call at a time',
    related: ['Rust', 'Three.js'],
    projects: ['nexagon'],
  },
  {
    name: 'CUDA',
    group: 'tools',
    category: 'graphics',
    level: 1,
    difficulty: 5,
    desc: 'Parallel GPU computing for ML and simulation.',
    funLevel: 'melts GPUs for fun',
    related: ['C/C++'],
    projects: [],
  },
  {
    name: 'OpenGL',
    group: 'tools',
    category: 'graphics',
    level: 2,
    difficulty: 4,
    desc: 'Cross-platform 2D/3D graphics API.',
    funLevel: 'deprecated but still standing',
    related: ['C/C++', 'Three.js'],
    projects: [],
  },
  {
    name: 'Linux',
    group: 'tools',
    category: 'DevOps',
    level: 4,
    difficulty: 3,
    desc: 'Daily driver OS — shell, containers, and servers.',
    funLevel: 'arch btw',
    related: ['Docker', 'Git', 'Node.js'],
    projects: ['nexagon', 'bank-rest-api-app'],
  },
];
