import {
  Home,
  User,
  Lightning,
  Briefcase,
  FolderClosed,
  FileText,
  Star,
  Envelope,
  ChartActivity,
  Message,
  ArrowRight,
  Box,
  Crosshair,
  Robot,
  Database,
  BookOpen,
} from '@/shared/ui/Icon';
import type { NavItem } from './navTypes';

/** Site-wide navigation — single source of truth.
    Groups split into `featured` cards + plain links in the dropdown. */
export const GLOBAL_NAV: NavItem[] = [
  {
    id: 'home',
    type: 'group',
    label: 'home',
    icon: Home,
    href: '/',
    children: [
      {
        id: 'about',
        type: 'section',
        label: 'About Me',
        description: 'Background, education & what drives me.',
        targetId: 'about',
        icon: User,
        featured: true,
      },
      {
        id: 'experience',
        type: 'section',
        label: 'My Journey',
        description: 'Roles, timeline & key milestones.',
        targetId: 'experience',
        icon: Briefcase,
        featured: true,
      },
      {
        id: 'projects-nav',
        type: 'route',
        label: 'View Projects',
        href: '/projects',
        icon: FolderClosed,
      },
      {
        id: 'blog-nav',
        type: 'route',
        label: 'Read Blog',
        href: '/blog',
        icon: FileText,
      },
      {
        id: 'reviews-nav',
        type: 'section',
        label: 'Leave a Review',
        targetId: 'reviews',
        icon: Message,
      },
      {
        id: 'contact-nav',
        type: 'section',
        label: 'Contact Me',
        targetId: 'contact',
        icon: Envelope,
      },
    ],
  },
  {
    id: 'projects',
    type: 'group',
    label: 'projects',
    icon: FolderClosed,
    href: '/projects',
    children: [
      {
        id: 'proj-nexagon',
        type: 'route',
        label: 'Nexagon',
        description: 'Game server monitoring — Rust, React, WebGPU.',
        href: '/projects/nexagon',
        icon: Lightning,
        featured: true,
        image: '/media/projects/nexagon/images/nexagon_main.webp',
      },
      {
        id: 'proj-bloxingbad',
        type: 'route',
        label: 'BloxingBad',
        description: 'PvP combat systems on Roblox.',
        href: '/projects/bloxingbad',
        icon: Crosshair,
        featured: true,
        image: '/media/projects/bloxingbad/images/map-reference.webp',
      },
      {
        id: 'proj-gmod',
        type: 'route',
        label: 'GMod × Roblox',
        description: 'Garry’s Mod sandbox, rebuilt as a toybox.',
        href: '/projects/gmod-roblox',
        icon: Box,
        featured: true,
        image: '/media/projects/project-gmod/images/pgm_overview.webp',
      },
      {
        id: 'all-projects',
        type: 'route',
        label: 'All Projects',
        href: '/projects',
        icon: ArrowRight,
      },
      {
        id: 'home-stats',
        type: 'route',
        label: 'Stats & Activity',
        href: '/stats',
        icon: ChartActivity,
      },
    ],
  },
  {
    id: 'blog',
    type: 'group',
    label: 'blog',
    icon: BookOpen,
    href: '/blog',
    children: [
      {
        id: 'post-portfolio',
        type: 'route',
        label: 'Building My Portfolio',
        description: 'How this site was built from scratch.',
        href: '/blog/building-my-portfolio',
        icon: Star,
        featured: true,
        tint: '#fbbf24',
        glyph: '</>',
      },
      {
        id: 'post-orb',
        type: 'route',
        label: 'Discord Orb Quests',
        description: 'Automating quest grinding with a bot.',
        href: '/blog/discord-orb-quests',
        icon: Robot,
        featured: true,
        tint: '#5865F2',
        glyph: 'Terminal',
      },
      {
        id: 'post-nodejs',
        type: 'route',
        label: 'Node.js Backend',
        description: 'Integrating Node into the stack.',
        href: '/blog/integrating-nodejs',
        icon: Database,
        featured: true,
        tint: '#a78bfa',
        glyph: 'Server',
      },
      {
        id: 'all-posts',
        type: 'route',
        label: 'All Posts',
        href: '/blog',
        icon: ArrowRight,
      },
    ],
  },
  {
    id: 'stats',
    type: 'route',
    label: 'stats',
    href: '/stats',
    icon: ChartActivity,
    match: 'exact',
  },
];

/** Home section IDs — used for scroll observer on the landing page */
export const HOME_SECTION_IDS = [
  'about',
  'experience',
  'projects',
  'reviews',
  'contact',
] as const;
